---
title: "Environmental Identity (EID)"
---

Model pengukuran unidimensional murni untuk EID (14 aitem).

```{r}
#| label: setup-cfa-eid
#| include: false

source("R/helpers.R")
df <- readRDS("data/cleaned_data.rds")
```

```{r}
#| label: cfa-eid
model_eid <- "
  EID =~ EID_1 + EID_2 + EID_3 + EID_4 + EID_5 + EID_6 + EID_7 + EID_8 + EID_9 + EID_10 + EID_11 + EID_12 + EID_13 + EID_14 
"
fit_eid <- cfa(model_eid, data = df, std.lv = TRUE, estimator = "MLR")
summary(fit_eid, fit.measures = TRUE, standardized = TRUE)

# Simpan hasil untuk halaman summary
saveRDS(fit_eid, "data/fit_eid.rds")
```


## Model Fit EID

```{r}
#| label: tbl-fit-eid
#| tbl-cap: "Fit Model EID"
print_fit_table(fit_eid, "EID")
```


## Visualisasi Model EID

```{r}
#| label: fig-cfa-eid
#| fig-cap: "Visualisasi CFA First-Order EID"
#| fig-width: 8
#| fig-height: 6
plot_cfa(fit_eid, "CFA Model EID (First-Order)")
```

## Reliabilitas EID

```{r}
#| label: tbl-rel-eid
#| tbl-cap: "Reliabilitas Skala EID"
print_rel_table(fit_eid)
```
