---
title: "Perceived Social Media Literacy (PSML)"
---

Correlated 4-factor multidimensional model (First-Order). *Purely theoretical.*

```{r}
#| label: setup-cfa-psmls
#| include: false

source("R/helpers.R")
df <- readRDS("data/cleaned_data.rds")
```

```{r}
#| label: cfa-psmls
model_psmls <- "
  TechComp =~ PSMLS_1 + PSMLS_2 + PSMLS_3 + PSMLS_4 + PSMLS_5
  SocialRel =~ PSMLS_6 + PSMLS_7 + PSMLS_8
  Privacy =~ PSMLS_9 + PSMLS_10 + PSMLS_11
  InfoAware =~ PSMLS_12 + PSMLS_13 + PSMLS_14
"
fit_psmls <- cfa(model_psmls, data = df, std.lv = TRUE, estimator = "MLR")
summary(fit_psmls, fit.measures = TRUE, standardized = TRUE)

saveRDS(fit_psmls, "data/fit_psmls.rds")
```


## Model Fit PSML

```{r}
#| label: tbl-fit-psmls
#| tbl-cap: "Model Fit PSML"
print_fit_table(fit_psmls, "PSML")
```


## Model Visualization PSML

```{r}
#| label: fig-cfa-psmls
#| fig-cap: "First-Order CFA Visualization PSML"
#| fig-width: 8
#| fig-height: 6
#| eval: false
plot_cfa(fit_psmls, "CFA Model PSML (First-Order)")
```

## Reliability PSML

```{r}
#| label: tbl-rel-psmls
#| tbl-cap: "Scale Reliability PSMLS (Dimensi)"
print_rel_table(fit_psmls)
```
