---
title: "Pro-Environmental Behavior (PEB)"
---

4-factor multidimensional model (First-Order). *Optimized with 3 MIs.*

```{r}
#| label: setup-cfa-peb
#| include: false

source("R/helpers.R")
df <- readRDS("data/cleaned_data.rds")
```

```{r}
#| label: cfa-peb
model_peb <- "
  ConsLife =~ PEB_1 + PEB_2 + PEB_3 + PEB_4 + PEB_5
  SocEnv =~ PEB_6 + PEB_7 + PEB_8 + PEB_9 + PEB_10
  EnvCit =~ PEB_11 + PEB_12 + PEB_13 + PEB_14 + PEB_15
  LandStew =~ PEB_16 + PEB_17
  PEB_7 ~~ PEB_8 
  PEB_9 ~~ PEB_10 
  PEB_2 ~~ PEB_3 
"
fit_peb <- cfa(model_peb, data = df, std.lv = TRUE, estimator = "MLR")
summary(fit_peb, fit.measures = TRUE, standardized = TRUE)

saveRDS(fit_peb, "data/fit_peb.rds")
```


## Model Fit PEB

```{r}
#| label: tbl-fit-peb
#| tbl-cap: "Model Fit PEB"
print_fit_table(fit_peb, "PEB")
```


## Model Visualization PEB

```{r}
#| label: fig-cfa-peb
#| fig-cap: "First-Order CFA Visualization PEB"
#| fig-width: 8
#| fig-height: 6
#| eval: false
plot_cfa(fit_peb, "CFA Model PEB (First-Order)")
```

## Reliability PEB

```{r}
#| label: tbl-rel-peb
#| tbl-cap: "Scale Reliability PEB (Dimensi)"
print_rel_table(fit_peb)
```
